access/urls.py
from django.urls import path
from . import views

# Name space to allow distinction between duplicate views in separate apps
app_name = 'access'

urlpatterns = [
    path('', views.signup, name='home'),
    path('signup', views.signup, name='signup'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout')
]

logs/urls.py
from django.urls import path
from . import views

# Name space to allow distinction between duplicate views in separate apps
app_name = 'logs'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:log_id>/', views.detail, name='detail'),
    path('<int:log_id>/comment', views.comment, name='add-comment'),
    path('create', views.create_log, name='create-log')
]

potential_market/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('access.urls')),
    path('logs/', include('logs.urls')),
    path('profiles/', include('profiles.urls')),
    path('settings/', include('settings.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

access/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone

default_avatar = "/default/default-avatar.jpg"


# Create your models here.
class CustomUser(AbstractUser):
    profile_picture = models.ImageField(upload_to='avatars', default=default_avatar)
    date_joined = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.username} joined on {self.date_joined}"

access/forms.py
from django import forms
from django.contrib.auth.hashers import check_password
from django.core.exceptions import ValidationError

from .models import CustomUser

max_username_len = 75
min_username_len = 1
min_password_len = 8


class SignupForm(forms.Form):
    username = forms.CharField(label='Username', max_length=max_username_len,
                               min_length=min_username_len, required=True)
    email = forms.EmailField(label='Email', required=True)
    password = forms.CharField(min_length=min_password_len,
                               widget=forms.PasswordInput(), required=True)

    def clean_username(self):
        uname = self.cleaned_data['username']
        if CustomUser.objects.filter(username=uname).exists():
            raise ValidationError("Username already exists")
        return uname

    def clean_email(self):
        email = self.cleaned_data['email']
        if CustomUser.objects.filter(email=email).exists():
            raise ValidationError("Email already exists")
        return email


class LoginForm(forms.Form):
    email = forms.EmailField(label='Email', required=True)
    password = forms.CharField(widget=forms.PasswordInput(), required=True)

    def clean(self):
        email = self.data['email']
        password = self.data['password']

        # Only validate if BOTH fields aren't empty
        # This helps to prevent multiple error messages for same issue
        # in login template, specifically the combination of
        # bad_credential_mess and "Field is required" messages
        if len(email) > 0 and len(password) > 0:
            bad_credential_mess = "Incorrect email/password combination"
            email = self.data['email']
            if not CustomUser.objects.filter(email=email).exists():
                raise ValidationError(bad_credential_mess)

            stored_user = CustomUser.objects.get(email=email)
            if not check_password(password, stored_user.password):
                raise ValidationError(bad_credential_mess)

access/views.py
from django.http import HttpResponseRedirect
from django.contrib.auth import login as django_login, logout as django_logout
from django.contrib.auth.hashers import check_password
from django.shortcuts import render
from django.urls import reverse

from .models import CustomUser
from .forms import SignupForm, LoginForm
from settings.models import Privacy


# Create your views here.
def signup(request):
    if request.method == 'POST':
        # Create form instance and populate it with data from request
        form = SignupForm(request.POST)
        if form.is_valid():
            # Process data in form.cleaned_data
            uname = form.cleaned_data.get('username')
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')

            # Create User model instance and store it in db
            user = CustomUser.objects.create_user(
                username=uname, email=email, password=password
            )
            Privacy.objects.create(user=user)
            # Set sessionid cookie to allow for identifying User in requests
            django_login(request, user)
            # Use redirect to prevent form resubmission
            return HttpResponseRedirect(reverse('logs:index'))

        # Redirect to same page and render error message
        return render(request, 'access/signup.html',
                      {'form': form}, status=400)

    elif request.user.is_authenticated:
        return HttpResponseRedirect(reverse('logs:index'))

    form = SignupForm()
    return render(request, 'access/signup.html', {'form': form})


def login(request):
    if request.method == 'POST':
        # Create form instance and populate it with data from request
        form = LoginForm(request.POST)
        if form.is_valid():
            # Process data in form.cleaned_data
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')

            # Find User instance if it exists and verify password.
            # If invalid, redirect to login form again
            user_set = CustomUser.objects.filter(email=email)
            if user_set.exists():
                user = user_set.get(email=email)
                if check_password(password, user.password):
                    # Set session cookie to identify User in requests
                    django_login(request, user)
                    return HttpResponseRedirect(reverse('logs:index'))

        # Redirect to same page and render error message
        return render(request, 'access/login.html',
                      {'form': form}, status=400)

    elif request.user.is_authenticated:
        return HttpResponseRedirect(reverse('logs:index'))

    form = LoginForm()
    return render(request, 'access/login.html', {'form': form})


def logout(request):
    if request.user.is_authenticated:
        django_logout(request)

    return HttpResponseRedirect(reverse('access:login'))

access/templates/access/login.html
{% extends 'base.html' %}

{% block title %}
    Login
{% endblock %}

{% block links %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'access/styles.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'access/layout.css' %}">
{% endblock %}

{% block body %}
    <main class="access-form">
        <h1 id="login-form-header"> 디지스트 재능마켓 </h1>
        <form id="login-form" action="{% url 'access:login' %}" method="post">
            {% csrf_token %}
            <div class="form-content">
                <h2> Login </h2>
                {# Still renders even if fields not entered #}
                {% if form.non_field_errors %}
                    <div class="error-message">
                        {{ form.non_field_errors }}
                    </div>
                {% endif %}
                {% for field in form %}
                    {% if field.errors %}
                        <div class="error-message"> {{ field.errors }} </div>
                    {% endif %}
                    <div class=input-field id="{{ field.name }}-input">
                        {{ field.label_tag }}
                        <br/>
                        {{ field }}
                    </div>
                    <br/>
                {% endfor %}
                <button type="submit"> Login </button>
            </div>
        </form>
    </main>
    <div>
        <p> Need an account? <a href="{% url 'access:signup' %}">Sign up</a> instead</p>
    </div>
{% endblock %}

access/templates/access/signup.html
{% extends 'base.html' %}

{% block title %}
    Sign Up
{% endblock %}

{% block links %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'access/styles.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'access/layout.css' %}">
{% endblock %}

{% block body %}
    <main class="access-form">
        <h1 id="signup-form-header"> 디지스트 재능마켓 </h1>
        <form class='input-form' id="signup-form" action="{% url 'access:signup' %}"
              method="post">
            {% csrf_token %}
            <div class="form-content">
                <h2> Sign Up </h2>
                {% for field in form %}
                    <div class="error-message"> {{ field.errors }} </div>
                    <div class=input-field id="{{ field.name }}-input">
                        {{ field.label_tag }}
                        <br/>
                        {{ field }}
                    </div>
                    <br/>
                {% endfor %}
                <button type="submit"> Sign Up </button>
            </div>
        </form>
    </main>
    <div>
        <p> Already signed up? <a href="{% url 'access:login' %}">Login</a> instead</p>
        <br/><br/>
        <p>
            On the fence about signing up? Check out some user logs
            <a href={% url 'logs:index' %}> here </a>
        </p>
    </div>
{% endblock %}