logs/urls.py
from django.urls import path
from . import views

# Name space to allow distinction between duplicate views in separate apps
app_name = 'logs'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:log_id>/', views.detail, name='detail'),
    path('<int:log_id>/comment', views.comment, name='add-comment'),
    path('create', views.create_log, name='create-log')
]

potential_market/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('access.urls')),
    path('logs/', include('logs.urls')),
    path('profiles/', include('profiles.urls')),
    path('settings/', include('settings.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

settings/urls.py
from django.urls import path
from . import views

# Name space to allow distinction between duplicate views in separate apps
app_name = 'settings'

urlpatterns = [
    path('', views.index, name='index'),
    path('password', views.password, name='password'),
    path('email', views.email, name='email'),
    path('delete', views.delete, name='delete-acc'),
    path('privacy', views.privacy, name='privacy'),
]

settings/models.py
from django.db import models

from access.models import CustomUser


# Create your models here.
class Privacy(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    show_logs = models.BooleanField(default=True, verbose_name="Make logs public")

    def __str__(self):
        return f"{self.user.username}'s log privacy settings set to {self.show_logs}"

settings/forms.py
from django import forms
from django.core.exceptions import ValidationError

from access.models import CustomUser
from access.forms import min_password_len


class PasswordForm(forms.ModelForm):
    password = forms.CharField()
    confirm_password = forms.CharField()

    class Meta:
        model = CustomUser
        fields = ['password']
        widgets = {
            'password': forms.PasswordInput(),
            'confirm_password': forms.PasswordInput(),
        }

    def clean_password(self):
        password = self.data['password']
        if len(password) < min_password_len:
            raise ValidationError("Invalid password length")

        return password

    def clean(self):
        password = self.data['password']
        confirmation = self.data['confirm_password']
        if password != confirmation:
            raise ValidationError("Passwords do not match!")


class EmailForm(forms.ModelForm):
    email = forms.CharField()

    class Meta:
        model = CustomUser
        fields = ['email']
        widgets = {
            'email': forms.EmailInput(),
        }

    def clean_email(self):
        email = self.cleaned_data['email']
        if CustomUser.objects.filter(email=email).exists():
            raise ValidationError("Email already in use!")

        return email


class DeleteForm(forms.ModelForm):
    password = forms.CharField(label='Confirm password to execute this action')

    class Meta:
        model = CustomUser
        fields = ['password']
        widgets = {
            'password': forms.PasswordInput()
        }

settings/views.py
import os.path

from django.shortcuts import render, reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password
from django.contrib.auth import logout

from .forms import PasswordForm, EmailForm, DeleteForm
from access.models import CustomUser, default_avatar
from logs.models import Log
from .models import Privacy


@login_required
def index(request):
    return render(request, 'settings/index.html')


@login_required
def password(request):
    context = {}

    if request.method == 'POST':
        form = PasswordForm(request.POST)
        if form.is_valid():
            user = CustomUser.objects.get(pk=request.user.id)
            user.password = make_password(form.cleaned_data['password'])
            user.save()
        else:
            context['form'] = form
            return render(request, 'settings/password.html', context)

        # User needs to login again
        return HttpResponseRedirect(reverse('access:login'))

    context['form'] = PasswordForm()
    return render(request, 'settings/password.html', context)


@login_required
def email(request):
    context = {}

    if request.method == 'POST':
        form = EmailForm(request.POST)
        if form.is_valid():
            user = CustomUser.objects.get(pk=request.user.id)
            user.email = form.cleaned_data['email']
            user.save()
        else:
            context['form'] = form
            return render(request, 'settings/email.html', context)

        # Make user login again
        logout(request)
        return HttpResponseRedirect(reverse('access:login'))

    context['form'] = EmailForm()
    return render(request, 'settings/email.html', context)


@login_required
def delete(request):
    context = {}

    if request.method == 'POST':
        form = DeleteForm(request.POST)
        if form.is_valid():
            # Still need to validate correct password
            user = CustomUser.objects.get(pk=request.user.id)
            if user.check_password(form.cleaned_data['password']):
                delete_account_data(user)
                return HttpResponseRedirect(reverse('access:signup'))

        context['error'] = 'Incorrect password!'
        context['form'] = DeleteForm()
        return render(request, 'settings/delete.html', context)

    context['form'] = DeleteForm()
    return render(request, 'settings/delete.html', context)


@login_required
def privacy(request):
    context = {}

    user_privacy_settings = Privacy.objects.get(user=request.user.id)

    if request.method == 'POST':
        log_setting_choice = request.POST['log-setting']
        user_privacy_settings.show_logs = log_setting_choice
        user_privacy_settings.save()
        return HttpResponseRedirect(reverse('settings:privacy'))

    # Send render value of log setting checkbox
    context['logValue'] = user_privacy_settings.show_logs
    return render(request, 'settings/privacy.html', context)


def delete_account_data(user: CustomUser):
    logs = Log.objects.filter(creator=user.id)

    # Delete all log images
    for log in logs:
        img_path = log.food.image.path
        if os.path.exists(img_path):
            os.remove(img_path)

    # Delete profile picture
    if user.profile_picture != default_avatar:
        pro_pic_path = user.profile_picture.path
        if os.path.exists(pro_pic_path):
            os.remove(pro_pic_path)

    user.delete()

settings/templates/settings/delete.html
{% extends 'base.html' %}

{% block title %}
    Delete Account
{% endblock %}

{% block links %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'settings/styles.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'settings/layout.css' %}">
{% endblock %}

{% block body %}
    <h1> Delete Your Account </h1>
    <form id="email-form" action="{% url 'settings:delete-acc' %}" method="post">
        {% csrf_token %}
        <div id="form-fields">
            {% if error %}
                <p class="error-message"> {{ error }} </p>
            {% endif %}
            {% for field in form %}
                <div class="error-message"> {{ field.errors }} </div>
                <div class="input-field">
                    {{ field.label_tag }}
                    <br/>
                    {{ field }}
                </div>
                <br/>
            {% endfor %}
            <button type="submit"> Delete Your Account </button>
        </div>
    </form>
{% endblock %}

settings/templates/settings/email.html
{% extends 'base.html' %}

{% block title %}
    Change Email
{% endblock %}

{% block links %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'settings/styles.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'settings/layout.css' %}">
{% endblock %}

{% block body %}
    <h1> Change Your Email </h1>
    <form id="email-form" action="{% url 'settings:email' %}" method="post">
        {% csrf_token %}
        <div id="form-fields">
            {# Only render general error message if no field-specific ones exist #}
            {% if form.errors|length == form.non_field_errors|length %}
                {% for err in form.non_field_errors %}
                    <div class="form-error-message">
                        {{ err }}
                    </div>
                {% endfor %}
                <br/>
            {% endif %}
            {% for field in form %}
                <div class="error-message"> {{ field.errors }} </div>
                <div class="input-field">
                    {{ field.label_tag }}
                    <br/>
                    {{ field }}
                </div>
                <br/>
            {% endfor %}
            <button type="submit"> Change Email </button>
        </div>
    </form>
{% endblock %}

settings/templates/settings/index.html
{% extends 'base.html' %}

{% block title %}
    Settings
{% endblock %}

{% block links %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href={% static 'settings/layout.css' %}>
{% endblock %}

{% block body %}
    <h1> Settings </h1>
    <a href="{% url 'settings:password' %}"> Change Password </a> <br/><br/>
    <a href="{% url 'settings:email' %}"> Change Email </a> <br/><br/>
    <a href="{% url 'settings:privacy' %}"> Change Privacy Settings </a> <br/><br/>
    <a href="{% url 'settings:delete-acc' %}"> Delete Account </a> <br/><br/>
{% endblock %}

settings/templates/settings/password.html
{% extends 'base.html' %}

{% block title %}
    Change Password
{% endblock %}

{% block links %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'settings/styles.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'settings/layout.css' %}">
{% endblock %}

{% block body %}
    <h1> Change Your Password </h1>
    <form id="password-form" action="{% url 'settings:password' %}" method="post">
        {% csrf_token %}
        <div id="form-fields">
            {# Only render general error message if no field-specific ones exist #}
            {% if form.errors|length == form.non_field_errors|length %}
                {% for err in form.non_field_errors %}
                    <div class="form-error-message">
                        {{ err }}
                    </div>
                {% endfor %}
                <br/>
            {% endif %}
            {% for field in form %}
                <div class="error-message"> {{ field.errors }} </div>
                <div class="input-field">
                    {{ field.label_tag }}
                    <br/>
                    {{ field }}
                </div>
                <br/>
            {% endfor %}
            <button type="submit"> Change Password </button>
        </div>
    </form>
{% endblock %}

settings/templates/settings/privacy.html
{% extends 'base.html' %}

{% block title %}
    Privacy Settings
{% endblock %}

{% block links %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'settings/styles.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'settings/layout.css' %}">
{% endblock %}

{% block body %}
    <h1> Privacy Settings </h1>
    <form id="privacy-form" action="{% url 'settings:privacy' %}" method="post">
        {% csrf_token %}
        <label for="log-setting"> Logs Are Public </label>
        {# Provides false value if checkbox unchecked #}
        <input type="hidden" name="log-setting" value="False" />
        {% if logValue == True %}
            <input type="checkbox" id='log-setting' value="True" name="log-setting" checked/>
        {% else %}
            <input type="checkbox" id='log-setting' value="True" name="log-setting"/>
        {% endif %}
        <button type="submit"> Save Changes </button>
    </form>
{% endblock %}