access/urls.py
from django.urls import path
from . import views

# Name space to allow distinction between duplicate views in separate apps
app_name = 'access'

urlpatterns = [
    path('', views.signup, name='home'),
    path('signup', views.signup, name='signup'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout')
]

logs/urls.py
from django.urls import path
from . import views

# Name space to allow distinction between duplicate views in separate apps
app_name = 'logs'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:log_id>/', views.detail, name='detail'),
    path('<int:log_id>/comment', views.comment, name='add-comment'),
    path('create', views.create_log, name='create-log')
]

potential_market/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('access.urls')),
    path('logs/', include('logs.urls')),
    path('profiles/', include('profiles.urls')),
    path('settings/', include('settings.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/urls.py
from django.urls import path
from . import views

# Name space to allow distinction between duplicate views in separate apps
app_name = 'profiles'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:user_id>/', views.user, name='user')
]

settings/urls.py
from django.urls import path
from . import views

# Name space to allow distinction between duplicate views in separate apps
app_name = 'settings'

urlpatterns = [
    path('', views.index, name='index'),
    path('password', views.password, name='password'),
    path('email', views.email, name='email'),
    path('delete', views.delete, name='delete-acc'),
    path('privacy', views.privacy, name='privacy'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> {% block title %} {% endblock %} </title>

    {% load static %}
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'favicon.ico' %}">
    <link rel="stylesheet" type="text/css" href={% static 'styles.css' %}>
    <link rel="stylesheet" type="text/css" href={% static 'nav-layout.css' %}>
    <link rel="stylesheet" type="text/css" href={% static 'nav-style.css' %}>
    {% block links %} {% endblock %}
</head>
<body>
    {% block body %} {% endblock %}
    <br/> <br/>
</body>
<footer>
    {% if user.is_authenticated %}
        <nav class="navbar">
            <a id="home" href={% url 'logs:index' %}> 홈 </a>
            <a id="nav-users" href={% url 'profiles:index' %}> 유저들 </a>
            <a id="nav-create-log" href={% url 'logs:create-log' %}> 재능등록 </a>
            <a id="nav-profile" href={% url 'profiles:user' user.id %}> 프로필 </a>
            <a id="nav-settings" href={% url 'settings:index' %}> 세팅 </a>
            <a id="nav-logout" href={% url 'access:logout' %}> 로그아웃 </a>
        </nav>
    {% endif %}
</footer>
</html>