access/urls.py
from django.urls import path
from . import views

# Name space to allow distinction between duplicate views in separate apps
app_name = 'access'

urlpatterns = [
    path('', views.signup, name='home'),
    path('signup', views.signup, name='signup'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout')
]

logs/urls.py
from django.urls import path
from . import views

# Name space to allow distinction between duplicate views in separate apps
app_name = 'logs'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:log_id>/', views.detail, name='detail'),
    path('<int:log_id>/comment', views.comment, name='add-comment'),
    path('create', views.create_log, name='create-log')
]

potential_market/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('access.urls')),
    path('logs/', include('logs.urls')),
    path('profiles/', include('profiles.urls')),
    path('settings/', include('settings.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/urls.py
from django.urls import path
from . import views

# Name space to allow distinction between duplicate views in separate apps
app_name = 'profiles'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:user_id>/', views.user, name='user')
]

logs/models.py
from datetime import timedelta

from django.utils import timezone
from django.db import models

from access.models import CustomUser


class Food(models.Model):
    creator = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    name = models.CharField('판매할 재능',max_length=200)
    desc = models.CharField('description', max_length=1000)
    ingredients = models.CharField(max_length=500)
    calories = models.IntegerField(default=0)
    image = models.ImageField(upload_to='logs', null=True, blank=True,
                              verbose_name='Image (Optional)')

    def __str__(self):
        return f"{self.name} contributed {self.calories} calories."


class Log(models.Model):
    creator = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    food = models.OneToOneField(Food, on_delete=models.CASCADE)
    pub_date = models.DateTimeField('Date published')

    def __str__(self):
        return f"{self.creator.username} ate {self.food.name} on {self.pub_date.date()}."


class Comment(models.Model):
    creator = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    log = models.ForeignKey(Log, on_delete=models.CASCADE)
    comment = models.CharField(max_length=1000)
    pub_date = models.DateTimeField('Date commented')

    def __str__(self):
        return f"{self.creator.username} said {self.comment} on {self.pub_date.date()} "

    def is_recent(self):
        now = timezone.now()
        return now - timedelta(days=1) <= self.pub_date <= now

logs/forms.py
from django import forms
from django.forms import ModelForm, Textarea

from .models import Food


class FoodForm(ModelForm):
    class Meta:
        model = Food
        fields = ['name', 'desc', 'ingredients', 'image']
        fields = ['name', 'desc', 'image']
        widgets = {
            'desc': Textarea(),
            #'ingredients': Textarea({"placeholder": "chicken breast, string beans, 1 cup white rice"}),
        }
        labels = {
            'desc': f'설명 '
            f'(카카오톡 아이디나 문자받을 전화번호를 꼭 남겨주세요)'
    
        }
        

class LogSearchForm(forms.Form):
    query = forms.CharField(label='고수의 이름이나 주제를 입력해주세요', required=False)

logs/views.py
import os

from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.utils import timezone
from django.db.models import Q

from .models import Food, Log, Comment
from .forms import FoodForm, LogSearchForm
from settings.models import Privacy

import requests

# Should list all logs globally like some sort of home page feed
# Taking into account user privacy settings
def index(request):
    context = {}

    public_log_filter = get_privacy_settings(True)
    latest_logs = Log.objects.filter(
        pub_date__lte=timezone.now(), creator__in=public_log_filter).order_by('-pub_date')

    if request.method == 'POST':
        query_form = LogSearchForm(request.POST)
        if query_form.is_valid():
            # Might be better to separate query options into separate forms
            query = query_form.cleaned_data['query']
            latest_logs = latest_logs.filter(
                Q(creator__username__icontains=query) | Q(food__name__icontains=query)
            ).order_by('-pub_date')

    context['latest_logs'] = latest_logs
    context['form'] = LogSearchForm(request.POST)
    return render(request, 'logs/index.html', context)


def detail(request, log_id):
    context = {}

    log = get_object_or_404(Log, pk=log_id)
    log_privacy = Privacy.objects.get(user=log.creator.id)
    comments = log.comment_set.filter(pub_date__lte=timezone.now())

    if not log_privacy.show_logs and request.user.id != log.creator.id:
        context['privacyMessage'] = 'You do not have permission to view this log!'
    else:
        context['log'] = log
        context['comment_list'] = comments

    if request.method == 'POST':
        if request.user == log.creator:
            # One to one in log means log depends on food.
            # Deleting food will cascade log, but not vice versa
            log.food.delete()
            return HttpResponseRedirect(reverse('logs:index'))

    return render(request, 'logs/detail.html', context)


def create_log(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('access:signup'))

    if request.method == 'POST':
        # Create form instance and populate it with data from request
        form = FoodForm(request.POST, request.FILES)
        if form.is_valid():
            # Process data in form.cleaned_data
            food_name = form.cleaned_data['name']
            desc = form.cleaned_data['desc']
            #ingreds = form.cleaned_data['ingredients']
            img = form.cleaned_data.get('image')

            # Calculate calories based off ingredients provided
            #ingred_json = fetchIngredientData(ingreds)
            #calories = parseCalorieData(ingred_json)

            #food_obj = Food(creator=request.user, name=food_name, desc=desc,
            #                ingredients=ingreds, calories=calories, image=img)
            food_obj = Food(creator=request.user, name=food_name, desc=desc,
                             image=img)
            food_obj.save()

            log = Log(creator=request.user, food=food_obj, pub_date=timezone.now())
            log.save()
            return HttpResponseRedirect(reverse('logs:index'))

        # Redirect to same page and render error message
        return render(request, 'logs/create-log.html',
                      {'form': form}, status=400)

    form = FoodForm()

    return render(request, 'logs/create-log.html', {'form': form})


def comment(request, log_id):
    if not request.method == 'POST':
        return HttpResponseRedirect(reverse('logs:detail', args=(log_id,)))

    # Unauthenticated cannot comment
    if request.user.is_authenticated:
        log = get_object_or_404(Log, pk=log_id)
        # Authenticated user cannot comment on other users' PRIVATE logs
        log_privacy = Privacy.objects.get(user=log.creator.id)
        if not log_privacy.show_logs and request.user != log.creator:
            return HttpResponseRedirect(reverse('logs:index'))

        try:
            comment_data = request.POST['comment-text']
        except (KeyError, Comment.DoesNotExist):
            error_message = 'Error getting comment data. Please try again!'
            return render(request, 'logs/detail.html', {'log': log,
                                                        'comment_list': log.comment_set.all(),
                                                        'error_message': error_message})
        # Get user currently signed in
        if len(comment_data.strip()) > 0:
            # request.user exists due to session cookie
            # created after login/signup
            commenter = request.user
            log = Log.objects.get(pk=log_id)

            new_comment = Comment(creator=commenter, log=log, comment=comment_data,
                                  pub_date=timezone.now())

            new_comment.save()
    # Redirect to prevent post data from being reused in case of back button click
    return HttpResponseRedirect(reverse('logs:detail', args=(log_id,)))


def get_privacy_settings(privacy_setting: bool):
    return Privacy.objects.filter(show_logs=privacy_setting).values_list('id')


# https://developer.edamam.com/food-database-api-docs for API documentation
def fetchIngredientData(ingredientsStr: str):
    ingredients = ingredientsStr.split(',')
    # URL encode ' '
    ingred_query = '%20and%20'.join(ingredients)

    # Get the Parsed response
    query_url = 'https://api.edamam.com/api/food-database/v2/parser'
    query_url += f'?app_id={os.getenv("APP_ID")}&app_key={os.getenv("APP_KEY")}'
    query_url += f'&ingr={ingred_query}&nutrition-type=cooking'

    response_json = requests.get(query_url).json()
    ingred_json = response_json.get('parsed')
    # print(ingred_json)
    return ingred_json


def parseCalorieData(ingredients_json_list):
    total_calories = 0

    for ingred_dict in ingredients_json_list:
        # print(ingred_dict.get('food'))
        nutrition_dict = ingred_dict.get('food').get('nutrients')
        total_calories += nutrition_dict.get('ENERC_KCAL')

    return total_calories

logs/templates/logs/create-log.html
{% extends 'logs/logs_base.html' %}

{% block page_title %}
    Create a Log
{% endblock %}

{% block page_links %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'logs/create-log.css' %}">
{% endblock %}

{% block content %}
    <h1> 판매하실 재능을 등록해주세요 </h1>
    <main class="main-content">
        <section class="food-log-form">
            {% if user.is_authenticated %}
                <form id="log-form" action="{% url 'logs:create-log' %}" method="post"
                enctype="multipart/form-data">
                    {% csrf_token %}
                    <div id="form-fields">
                        {% for field in form %}
                            <div class="error-message"> {{ field.errors }} </div>
                            <div class="input-field">
                                {{ field.label_tag }}
                                <br/>
                                {{ field }}
                            </div>
                            <br/>
                        {% endfor %}
                        <button type="submit"> 재능등록 </button>
                    </div>
                </form>
            {% else %}
                <h2>
                    You must be <a href="{% url 'access:signup' %}">logged in</a> to create a log!
                </h2>
            {% endif %}
        </section>
    </main>
    <br/><br/>
{% endblock %}

logs/templates/logs/detail.html
{% extends "logs/logs_base.html" %}

{% block page_title %}
    {{ log.creator.username }}'s Log
{% endblock %}

{% block page_links %}
    <script src="https://developer.edamam.com/attribution/badge.js"></script>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'logs/detail-style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'logs/detail-layout.css' %}">
{% endblock %}

{% block content %}
    {% load static %}
    <main class="food-log-data">
        {% if privacyMessage %}
            {{ privacyMessage }}
        {% else %}
            <div class="log-container">
                <h1> {{ log.food.name }} </h1>
                <div class="log-body">
                    <div class="log-food-info">
                        <h2 class="body-header"> Description </h2>
                        <p class="body-text textarea-output"> {{ log.food.desc }} </p>
                    </div>
                </div>
                <br/>
                {% if log.food.image %}
                    <img class="log-image" src='{{ log.food.image.url }}' alt='log-image' />
                {% endif %}
                <br/>
                <div class="log-footer">
                    <h3>
                        <a href="{% url 'profiles:user' log.creator.id %}">
                            {{ log.creator.username }}
                        </a>
                        <br/>
                        {{ log.pub_date }}
                    </h3>
                </div>
                {% if user.email == log.creator.email %}
                    <form id="delete-form" action="{% url 'logs:detail' log.id %}" method="post">
                        {% csrf_token %}
                        <button type="submit"> Delete log </button>
                    </form>
                {% endif %}
                <br/>
            </div>
        {% endif %}
    </main>

    {% if not privacyMessage %}
        <section id="comments">
            <h2 id="comment-header"> {{ comment_list|length }} Comments </h2>
            {% if user.is_authenticated %}
                <form id="comment-form" action="{% url 'logs:add-comment' log.id %}" method="post">
                    {% csrf_token %}
                    <label for="comment-text"></label>
                    <textarea minlength="1" id="comment-text" name="comment-text"
                              placeholder="Add a comment" required></textarea>
                    <br/>
                    <button type="submit"> Comment </button>
                </form>
            {% else %}
                <p class="authenticate-message">
                    <a href="{% url 'access:signup' %}">Sign up</a> to leave a comment!
                </p>
            {% endif %}
            <br/>
            {# Render comment list #}
            {% if comment_list %}
                <div id="comment-list-container">
                    {% for comment in comment_list %}
                        <div class="post-container">
                            <div class="post-header">
                                <img alt="Profile Icon" class="profile-icon"
                                     src="{{ comment.creator.profile_picture.url }}"/>
                            </div>
                            <div class="post-body">
                                <div class="post-body-data">
                                    <div class="username-text">
                                        <a href="{% url 'profiles:user' comment.creator.id %}">
                                            {{ comment.creator.username }}
                                        </a>
                                    </div>
                                    <div class="comment-date"> {{ comment.pub_date.date }} </div>
                                </div>
                                <p class="comment-body textarea-output"> {{ comment.comment }} </p>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            {% else %}
                <p id="no-comments-message"> Be the first to comment. </p>
            {% endif %}
        </section>
        {% if error_message %}
            <p> {{ error_message }} </p>
        {% endif %}
    {% endif %}
{% endblock %}

logs/templates/logs/index.html
{% extends 'logs/logs_base.html' %}

{% block page_title %}
    Logs Index
{% endblock %}

{% block page_links %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'logs/index-style.css' %}">
{% endblock %}



{% block content %}
    <h1>
        {% if user.is_authenticated %}
            Hi {{ user.username }}! 당신의 재능을 판매하거나, 고수의 재능을 구매해보세요
        {% else %}
            당신의 재능을 판매해보세요 -
            <a href="{% url 'access:signup' %}"> Sign Up </a>
        {% endif %}
    </h1>
    <form action="{% url 'logs:index' %}" method="POST">
        {% csrf_token %}
        {{ form }}
    </form>
    <br/>
    <main class="main-content">
        <section class="food-log-data">
            {% if latest_logs %}
                <ul>
                {% for log in latest_logs %}
                    <li>
                    <div class="log-entry-container">
                        <img class="food-icon" alt='Log Icon'
                             src="{{ log.creator.profile_picture.url }}"/>
                        <p class="log-entry-details">
                            <a href="{% url 'profiles:user' log.creator.id %}">
                                {{ log.creator.username }}
                            </a>
                            uploaded
                            <a href="{% url 'logs:detail' log.id %}">
                                {{ log.food.name }}
                            </a>
                            log on {{ log.pub_date.date }}
                        </p>
                    </div>
                    </li>
                {% endfor %}
                </ul>
            {% else %}
                <p> No logs are available. </p>
            {% endif %}
        </section>
    </main>
    <br/>
    <br/>
    {% if user.is_authenticated %}
        <a id="create-log-redirect" href="{% url 'logs:create-log' %}">
            판매하실 재능을 올려주세요
        </a>
    {% endif %}
    <br/><br/>
{% endblock %}

logs/templates/logs/logs_base.html
{% extends 'base.html' %}

{% block title %}
    {% block page_title %} {% endblock %}
{% endblock %}

{% block links %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'logs/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'logs/layout.css' %}">
    {% block page_links %} {% endblock %}
{% endblock %}

{% block body %}
   {% block content %} {% endblock %}
{% endblock %}